title: HOU XIWANG's Homepage
page-top-title: Xiwang HOU
top-section-bg-text: Ocean Science
home-subtitle: HOU XIWANG&ensp;|&ensp;侯喜旺
copyright-text: '&copy; Xiwang HOU 2022-2026. All Rights Reserved.'
